PUT http://localhost/admin/register
Content-Type:application/json

{
  "aName": "admin",
  "aPassword": "123",
  "aConfidentiality": "1999",
  "aPhone": "120",
  "aEmail": "999@qq.com"
}

###
POST http://localhost/admin/login
Content-Type:application/json

{
  "aName": "sun",
  "aPassword": "123"
}

###
GET http://localhost:81/filmplayer/select
Content-Type: application/json


###
#获取电影表的数据
GET http://localhost:81/home/select
Content-Type: application/json